mongodb:
  string: "mongodb+srv://usrRoot:zudwY4-dynteb-bymdud@cluster1.mfzwg.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
  
fileSettings:
  folder: "C:/Users/ivanb/AnypointStudio/studio-workspace/agencies-db-consume/src/main/resources/write/"